# SPDX-License-Identifier: PMPL-1.0-or-later
name: NimblePublisher Site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: erlef/setup-beam@ee09b1e59bb240681c382eb1f0abc6a04af72764 # v1
        with:
          elixir-version: "1.15"
          otp-version: "26"
      - name: Fetch dependencies
        run: |
          cd site
          mix deps.get
      - name: Build site
        run: |
          cd site
          mix site.build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v4
        with:
          path: site/_site
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
